### ISSUE TITLE
Generating Eval 4 Agent Training Tasks

### ISSUE THREAD

**Issue by bainro** [NextCenturyCorporation/mcs-scene-generator#3]
I have put NYU style eval4 json scene files into agents_examples/. I then run the following command:

```
$ python generate_public_scenes.py -c 1 -p /tmp/lol -t AgentExamplesTraining
Traceback (most recent call last):
  File "generate_public_scenes.py", line 28, in <module>
    main(sys.argv)
  File "generate_public_scenes.py", line 24, in main
    scene_generator.generate_scenes_from_args(argv)
  File "/nfs/hpc/share/bainro/mcs-scene-generator/scene_generator.py", line 348, in generate_scenes_from_args
    self.generate_scenes(
  File "/nfs/hpc/share/bainro/mcs-scene-generator/scene_generator.py", line 185, in generate_scenes
    hypercubes = hypercube_factory.build(
TypeError: build() takes from 3 to 4 positional arguments but 5 were given

$ python
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import machine_common_sense
>>> machine_common_sense.__version__
'0.4.0'
>>> import ai2thor
>>> ai2thor.__version__
'2.2.0'
``` 

I tried on the main branch and on the 0.4.0 tags for both the main MCS repo & this scene generator repo, and got the same thing both times. Any help would be greatly appreciated :D

**Comment by ThomasSchellenbergNextCentury** [comment]
Hi @bainro , thanks for reporting this! It appears our Eval 4 updates to the agent scene generation code were never properly merged. I've just merged them into `master`, so you should be able to run your command now. Please let us know if you experience any more difficulties.
